export const APP_PERMISSIONS = {
    // Users
    CREATE_USER: 'CREATE_USER',
    VIEW_USERS: 'VIEW_USERS',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',

    // Products
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    VIEW_PRODUCTS: 'VIEW_PRODUCTS',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',

    // Categories
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    VIEW_CATEGORIES: 'VIEW_CATEGORIES',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',

    // Brands
    CREATE_BRAND: 'CREATE_BRAND',
    VIEW_BRANDS: 'VIEW_BRANDS',
    UPDATE_BRAND: 'UPDATE_BRAND',
    DELETE_BRAND: 'DELETE_BRAND',

    // Orders
    CREATE_ORDER: 'CREATE_ORDER',
    VIEW_ORDERS: 'VIEW_ORDERS',
    UPDATE_ORDER: 'UPDATE_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',

    // Quotations
    CREATE_QUOTATION: 'CREATE_QUOTATION',
    VIEW_QUOTATIONS: 'VIEW_QUOTATIONS',
    UPDATE_QUOTATION: 'UPDATE_QUOTATION',
    DELETE_QUOTATION: 'DELETE_QUOTATION',

    // Coupons
    CREATE_COUPON: 'CREATE_COUPON',
    VIEW_COUPONS: 'VIEW_COUPONS',
    UPDATE_COUPON: 'UPDATE_COUPON',
    DELETE_COUPON: 'DELETE_COUPON',

    // Locations
    CREATE_LOCATION: 'CREATE_LOCATION',
    VIEW_LOCATIONS: 'VIEW_LOCATIONS',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    DELETE_LOCATION: 'DELETE_LOCATION',

    // Home CMS
    VIEW_CMS: 'VIEW_CMS',
    UPDATE_CMS: 'UPDATE_CMS',
    UPLOAD_CMS_ASSETS: 'UPLOAD_CMS_ASSETS',

    // Settings
    VIEW_SETTINGS: 'VIEW_SETTINGS',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',

    // Others
    ACCESS_DASHBOARD: 'ACCESS_DASHBOARD',
    MANAGE_ROLES: 'MANAGE_ROLES',
    VIEW_REPORTS: 'VIEW_REPORTS'
} as const;

export type AppPermission = typeof APP_PERMISSIONS[keyof typeof APP_PERMISSIONS];
